import Math3D from "./Math3D";
import Point from "./entites/Point";
import Light from "./entites/Light";
import Polygon, { EDistance } from "./entites/Polygon";
import Sphere from "./surfaces/Sphere";
import Cube from "./surfaces/Cube";
import Ellipsoid from "./surfaces/Ellipsoid";
import Thor from "./surfaces/Thor";
import TwoSurfaceHyperboloid from "./surfaces/TwoSurfaceHyperboloid";
import EllipticCylinder from "./surfaces/EllipticCylinder";
import EllipticParaboloid from "./surfaces/EllipticParaboloid";
import HyperbolicCylinder from "./surfaces/HyperbolicCylinder";
import HyperbolicParaboloid from "./surfaces/HyperbolicParaboloid";
import OneSurfaceHyperboloid from "./surfaces/OneSurfaceHyperboloid";
import KleinBottle from "./surfaces/KleinBottle";
import Cone from "./surfaces/Cone";
import ParabolicCylinder from "./surfaces/ParabolicCylinder";

export { Point, Light, Polygon, Sphere, EDistance, Cube, Ellipsoid, Thor, TwoSurfaceHyperboloid, EllipticCylinder, EllipticParaboloid, HyperbolicCylinder, HyperbolicParaboloid, OneSurfaceHyperboloid, KleinBottle, Cone, ParabolicCylinder};
export default Math3D;